### ISSUE TITLE
designPDMLDetectorSingle.m errors

### ISSUE THREAD

**Issue by akeapen** [navSecurity/P-D-defense#1]
- designPDMLDetectorSingle.m errors due to Np, and other variables being undefined
- comment suggests that loading mpeIQMonteCarloall.mat can fix the issue 
- mpeIQMonteCarloall.mat is not included in any subfolder in the repo

**Comment by jsngross** [comment]
You have the tools needed to run the Monte Carlo and create this file. You must do this before calling the above referenced script
