### ISSUE TITLE
Missing dependent file from repo

### ISSUE THREAD

**Issue by akeapen** [navSecurity/P-D-defense#2]
Required file GPSCAAutoCorr.m is missing from calling functions: toeplitzQMatrix.m, multiTapMultipathEstimatorSingleModelBisect.m, defineObservationMat.m.

**Comment by jsngross** [comment]
All of the above reference files are present in the repo. They are located in the functions folder. You need to add this folder to your matlab path.

**Comment by akeapen** [comment]
Thank you Jason.  The following file is not present: GPSCAAutoCorr.m

**Comment by jsngross** [comment]
Sorry, Rcorr is there and should be a drop in replacement.

**Comment by akeapen** [comment]
Excellent, Jason.  Appreciate you sharing your important work.
